# Generated by Django 5.1.4 on 2026-01-29 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_userprofile_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
