# Generated by Django 5.1.4 on 2026-02-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_lister',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_renter',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('renter', 'Renter'), ('owner', 'Owner')], default='renter', max_length=10),
        ),
    ]
