# Generated by Django 5.1.4 on 2026-07-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_user_photo_url_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo_url',
        ),
    ]
