# Generated by Django 5.1.4 on 2026-07-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_remove_user_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
