# Generated by Django 5.0.7 on 2024-07-23 03:38

import Apps.Resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to=Apps.Resources.models.upload_to, validators=[Apps.Resources.models.ValidateImageFileExtension()])),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('item', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('startDate', models.DateField(max_length=200)),
                ('endDate', models.DateField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photos', models.ImageField(null=True, upload_to=Apps.Resources.models.upload_to, validators=[Apps.Resources.models.ValidateImageFileExtension()])),
                ('startDate', models.DateField(max_length=200, null=True)),
                ('endDate', models.DateField(max_length=200, null=True)),
                ('condition', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('deposit', models.CharField(max_length=255, null=True)),
                ('accessories', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('phoneNumber', models.IntegerField(null=True)),
                ('emailAddress', models.TextField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
