# Generated by Django 5.1 on 2024-08-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='emailAddress',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
