# Generated by Django 5.1.4 on 2026-07-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0002_remove_productimage_product_delete_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
