# Generated by Django 5.1.4 on 2025-01-06 14:26

import Apps.Resources.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0002_alter_products_emailaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='photos',
        ),
        migrations.AlterField(
            model_name='contactform1',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contactform1',
            name='startDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='startDate',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Apps.Resources.models.upload_to, validators=[Apps.Resources.models.ValidateImageFileExtension()])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Apps.Resources.products')),
            ],
        ),
    ]
