# Generated by Django 5.1.4 on 2025-04-18 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0004_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='FAQs',
            new_name='FAQ',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
