# Generated by Django 5.1.4 on 2026-07-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
