# Generated by Django 5.1.4 on 2026-02-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0002_alter_listing_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='emailAddress',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='name',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='phoneNumber',
        ),
    ]
