# Generated by Django 5.1.4 on 2026-02-16 09:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0003_remove_listing_emailaddress_remove_listing_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='products'),
        ),
    ]
