# Generated by Django 5.1.4 on 2026-02-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0005_remove_listing_image_listing_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
