# Generated by Django 5.0.6 on 2024-06-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=300)),
                ('Answer', models.CharField(max_length=500)),
                ('posted_on', models.DateField()),
            ],
        ),
    ]
