# Generated by Django 5.0.6 on 2024-06-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQs', '0002_remove_faqs_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='Answer',
            field=models.TextField(),
        ),
    ]
