# Generated by Django 5.0.6 on 2024-06-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAQs', '0003_alter_faqs_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqs',
            old_name='Answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='faqs',
            old_name='Question',
            new_name='title',
        ),
    ]
