# Generated by Django 5.0.6 on 2024-06-06 09:49

import Resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0002_faqs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image_url',
            field=models.ImageField(null=True, upload_to=Resources.models.upload_to),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
