# Generated by Django 5.0.6 on 2024-06-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0003_alter_categories_image_url_alter_categories_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='image_url',
            new_name='image',
        ),
    ]
