# Generated by Django 5.0.6 on 2024-06-10 03:55

import Resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0004_rename_image_url_categories_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producttype', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photos', models.ImageField(null=True, upload_to=Resources.models.upload_to)),
                ('brand', models.CharField(max_length=255)),
                ('functionalities', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('preferreduser', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('userconsiderations', models.CharField(max_length=255)),
            ],
        ),
    ]
