# Generated by Django 5.0.6 on 2024-06-11 07:12

import Resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0005_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='preferreduser',
            new_name='preferredUser',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='userconsiderations',
            new_name='usageconsiderations',
        ),
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(null=True, upload_to=Resources.models.upload_to, validators=[Resources.models.ValidateImageFileExtension()]),
        ),
        migrations.AlterField(
            model_name='products',
            name='photos',
            field=models.ImageField(null=True, upload_to=Resources.models.upload_to, validators=[Resources.models.ValidateImageFileExtension()]),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
