# Generated by Django 5.0.6 on 2024-06-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0006_rename_preferreduser_products_preferreduser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('item', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('startdate', models.DateField(max_length=200)),
                ('enddate', models.DateField(max_length=200)),
            ],
        ),
    ]
