# Generated by Django 5.0.6 on 2024-06-12 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0007_contactform1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform1',
            old_name='enddate',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='contactform1',
            old_name='startdate',
            new_name='startDate',
        ),
    ]
