# Generated by Django 5.0.6 on 2024-06-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0008_rename_enddate_contactform1_enddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='brand',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='functionalities',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='preferredUser',
        ),
        migrations.RemoveField(
            model_name='products',
            name='producttype',
        ),
        migrations.RemoveField(
            model_name='products',
            name='usageconsiderations',
        ),
        migrations.AddField(
            model_name='products',
            name='accessories',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='deposit',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='emailAddress',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='endDate',
            field=models.DateField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='phoneNumber',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='startDate',
            field=models.DateField(max_length=200, null=True),
        ),
    ]
