# Generated by Django 5.0.6 on 2024-06-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0009_rename_brand_products_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='phoneNumber',
            field=models.IntegerField(null=True),
        ),
    ]
